stages:
  - test

default:
  tags:
    - k8s
    - amd64
  before_script:
    - |
        curl "https://api.github.com/repos/qoretechnologies/${REPO_NAME}/statuses/${CI_COMMIT_SHA}" \
        -X POST --oauth2-bearer ${GITHUB_ACCESS_TOKEN} -H "Content-Type: application/json" \
        -d "{\"state\": \"pending\", \"context\": \"${REPO_NAME}\", \"description\": \"Gitlab CI\", \"target_url\": \"${CI_JOB_URL}\"}"
    - set +e

variables:
  REPO_NAME: module-v8
  GIT_SUBMODULE_STRATEGY: recursive

test-ubuntu:
  stage: test
  image: $CI_REGISTRY/infrastructure/qore-test-base/qore-test-base@sha256:b486c7fc4d87dbc75d69c89bb0b4e1dd946758113318611a2a98a92a654d6010
  script:
    - |
        if test/docker_test/test-ubuntu.sh; then
          curl "https://api.github.com/repos/qoretechnologies/${REPO_NAME}/statuses/${CI_COMMIT_SHA}" \
            -X POST --oauth2-bearer ${GITHUB_ACCESS_TOKEN} -H "Content-Type: application/json" \
            -d "{\"state\": \"success\", \"context\": \"${REPO_NAME}\", \"description\": \"Gitlab CI\", \"target_url\": \"${CI_JOB_URL}\"}"
          exit 0
        else
          curl "https://api.github.com/repos/qoretechnologies/${REPO_NAME}/statuses/${CI_COMMIT_SHA}" \
            -X POST --oauth2-bearer ${GITHUB_ACCESS_TOKEN} -H "Content-Type: application/json" \
            -d "{\"state\": \"failure\", \"context\": \"${REPO_NAME}\", \"description\": \"Gitlab CI\", \"target_url\": \"${CI_JOB_URL}\"}"
          exit 1
        fi
  artifacts:
    when: always
    paths:
      - qualification/
    expire_in: 7 days

test-alpine:
  stage: test
  image: $CI_REGISTRY/infrastructure/qore-test-base/qore-test-base@sha256:a04ebc8dfde3d564acd00f252f53650ce832321daeb40be24f46de705827f682
  script:
    - |
        if test/docker_test/test-alpine.sh; then
          curl "https://api.github.com/repos/qoretechnologies/${REPO_NAME}/statuses/${CI_COMMIT_SHA}" \
            -X POST --oauth2-bearer ${GITHUB_ACCESS_TOKEN} -H "Content-Type: application/json" \
            -d "{\"state\": \"success\", \"context\": \"${REPO_NAME}\", \"description\": \"Gitlab CI\", \"target_url\": \"${CI_JOB_URL}\"}"
          exit 0
        else
          curl "https://api.github.com/repos/qoretechnologies/${REPO_NAME}/statuses/${CI_COMMIT_SHA}" \
            -X POST --oauth2-bearer ${GITHUB_ACCESS_TOKEN} -H "Content-Type: application/json" \
            -d "{\"state\": \"failure\", \"context\": \"${REPO_NAME}\", \"description\": \"Gitlab CI\", \"target_url\": \"${CI_JOB_URL}\"}"
          exit 1
        fi
  artifacts:
    when: always
    paths:
      - qualification/
    expire_in: 7 days
