export const ASANA_APP_NAME = 'Asana';
export const ASANA_ALLOWED_PATHS = [
  '/tasks',
  '/tasks/{task_gid}',
  '/tasks/{task_gid}/subtasks',
  '/tasks/{task_gid}/dependencies',
  '/tasks/{task_gid}/dependents',
  '/tasks/{task_gid}/attachments',
  '/tasks/{task_gid}/stories',
  '/workspaces',
  '/workspaces/{workspace_gid}',
  '/users',
  '/users/{user_gid}',
  '/projects',
  '/projects/{project_gid}',
  '/projects/{project_gid}/tasks',
  '/sections',
  '/sections/{section_gid}',
  '/sections/{section_gid}/tasks',
  '/tags',
  '/tags/{tag_gid}',
  '/tags/{tag_gid}/tasks',
  '/teams',
  '/teams/{team_gid}',
  '/teams/{team_gid}/projects',
  '/webhooks',
  '/webhooks/{webhook_gid}',
  '/events',
  '/events/{event_gid}',
  '/portfolio_memberships',
  '/portfolios',
  '/portfolios/{portfolio_gid}',
  '/goals',
  '/goals/{goal_gid}',
];
export const ASANA_SWAGGER_API_PATH = '';
